// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Json_decode from "../node_modules/@glennsl/bs-json/src/Json_decode.bs.js";

function convertJsonToHitsDataType(res) {
  return {
          author: Json_decode.field("author", Json_decode.string, res),
          num_comments: Json_decode.field("num_comments", Json_decode.$$int, res),
          title: Json_decode.field("title", Json_decode.string, res),
          url: Json_decode.field("url", Json_decode.string, res),
          points: Json_decode.field("points", Json_decode.$$int, res)
        };
}

function convertJsonToHitsJsonType(res) {
  var items = Json_decode.at({
          hd: "hits",
          tl: /* [] */0
        }, (function (param) {
            return Json_decode.array(convertJsonToHitsDataType, param);
          }))(res);
  return {
          hits: items
        };
}

export {
  convertJsonToHitsDataType ,
  convertJsonToHitsJsonType ,
}
/* No side effect */
