// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SearchForm$FeSupportService from "./SearchForm.bs.js";

import './App.css'
;

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(SearchForm$FeSupportService.make, {}));
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
