// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Buttons(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setPages = match[1];
  var handlePrev = function (e) {
    setPages(function (pages) {
          return pages - 1 | 0;
        });
  };
  var handleNext = function (e) {
    setPages(function (pages) {
          return pages + 1 | 0;
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                      children: "Prev",
                      onClick: handlePrev
                    }),
                JsxRuntime.jsx("p", {
                      children: match[0]
                    }),
                JsxRuntime.jsx("button", {
                      children: "Next",
                      onClick: handleNext
                    })
              ],
              className: "btn-container"
            });
}

var make = Buttons;

export {
  make ,
}
/* react Not a pure module */
