// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Client from "react-dom/client";
import * as App$FeSupportService from "./App.bs.js";

import './index.css'
;

var domElement = document.querySelector("#root");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(React.createElement(App$FeSupportService.make, {}));
}

export {
  
}
/*  Not a pure module */
