// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function SearchForm(props) {
  var match = React.useState(function () {
        return "react";
      });
  var setSearchTerm = match[1];
  return JsxRuntime.jsxs("form", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Hacker News"
                    }),
                JsxRuntime.jsx("input", {
                      type: "text",
                      value: match[0],
                      onChange: (function (ev) {
                          var target = ev.target;
                          var value = target.value;
                          setSearchTerm(function (_prevValue) {
                                return value;
                              });
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "Submit",
                      type: "submit"
                    })
              ],
              className: "search-form"
            });
}

var make = SearchForm;

export {
  make ,
}
/* react Not a pure module */
