// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Webapi__Fetch from "rescript-webapi/src/Webapi/Webapi__Fetch.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function SearchForm(props) {
  var match = React.useState(function () {
        return "react";
      });
  var setSearchTerm = match[1];
  var $$fetch$1 = function () {
    return fetch("https://hn.algolia.com/api/v1/search?react", Webapi__Fetch.RequestInit.make("Get", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)).then(function (prim) {
                  return prim.json();
                }).then(function (res) {
                console.log("res", res);
                return Promise.resolve(res);
              });
  };
  React.useEffect((function () {
          $$fetch$1();
        }), []);
  return JsxRuntime.jsxs("form", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Hacker News"
                    }),
                JsxRuntime.jsx("input", {
                      type: "text",
                      value: match[0],
                      onChange: (function (ev) {
                          var target = ev.target;
                          var value = target.value;
                          setSearchTerm(function (_prevValue) {
                                return value;
                              });
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "Submit",
                      type: "submit"
                    })
              ],
              className: "search-form"
            });
}

var make = SearchForm;

export {
  make ,
}
/* react Not a pure module */
