// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as Fetch from "../node_modules/bs-fetch/src/Fetch.bs.js";
import * as React from "react";
import * as Js_promise from "../node_modules/rescript/lib/es6/js_promise.js";
import * as APIType$FeSupportService from "./APIType.bs.js";
import * as Stories$FeSupportService from "./Stories.bs.js";

function SearchForm(Props) {
  var match = React.useState(function () {
        return "React";
      });
  var setSearchTerm = match[1];
  var searchTerm = match[0];
  var match$1 = React.useState(function () {
        return {
                hits: []
              };
      });
  var setHits = match$1[1];
  var $$fetch$1 = function (param) {
    return Js_promise.then_((function (res) {
                  console.log(res);
                  var data = APIType$FeSupportService.convertJsonToHitsJsonType(res);
                  console.log(data);
                  Curry._1(setHits, (function (param) {
                          return data;
                        }));
                  return Promise.resolve(undefined);
                }), Js_promise.then_(Fetch.$$Response.json, fetch("https://hn.algolia.com/api/v1/search?query=" + searchTerm + "")));
  };
  React.useEffect((function () {
          $$fetch$1(undefined);
        }), [searchTerm]);
  return React.createElement("div", undefined, React.createElement("form", {
                  className: "search-form"
                }, React.createElement("h2", {
                      style: {
                        fontSize: "40px",
                        fontWeight: "700"
                      }
                    }, "Hacker News"), React.createElement("br", undefined), React.createElement("input", {
                      className: "form-input",
                      type: "text",
                      value: searchTerm,
                      onChange: (function (ev) {
                          var target = ev.target;
                          var value = target.value;
                          Curry._1(setSearchTerm, (function (_prevValue) {
                                  return value;
                                }));
                        })
                    })), React.createElement(Stories$FeSupportService.make, {
                  hits: match$1[0].hits
                }));
}

var make = SearchForm;

export {
  make ,
}
/* react Not a pure module */
