// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Stories(props) {
  return JsxRuntime.jsx("section", {
              className: "stories"
            });
}

var make = Stories;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
