// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";

function Stories(Props) {
  var hits = Props.hits;
  console.log(hits);
  return React.createElement("section", {
              className: "stories"
            }, Belt_Array.map(hits, (function (item) {
                    return React.createElement("article", {
                                key: item.title,
                                className: "story"
                              }, React.createElement("h4", {
                                    className: "title"
                                  }, item.title), React.createElement("p", {
                                    className: "info"
                                  }, String(item.points) + " points for " + item.author, React.createElement("span", undefined, item.author + " | "), String(item.num_comments) + " comments"), React.createElement("div", undefined, React.createElement("a", {
                                        className: "read-link",
                                        href: item.url,
                                        rel: "noopener noreferrer",
                                        target: "_blank"
                                      }, "read more")));
                  })));
}

var make = Stories;

export {
  make ,
}
/* react Not a pure module */
